plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '2.0.147'
}

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    maven { url = 'https://www.cursemaven.com' }
    maven { url = 'https://maven.architectury.dev/' }
    maven { url = 'https://thedarkcolour.github.io/KotlinForForge/' }
    mavenCentral()
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
        }
        server {
            server()
            programArgument '--nogui'
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "curse.maven:cobblemon-687131:${cobblemon_file_id}"
    implementation "curse.maven:radical-cobblemon-trainers-api-1152792:${rctapi_file_id}"
    implementation "curse.maven:rctmod-1009534:${rctmod_file_id}"
    implementation "dev.architectury:architectury-neoforge:${architectury_version}"
    implementation("thedarkcolour:kotlinforforge-neoforge:${kotlin_for_forge_version}") {
        exclude group: 'net.neoforged.fancymodloader', module: 'loader'
    }

    testImplementation platform('org.junit:junit-bom:5.13.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.code.gson:gson:2.10.1'
    testImplementation 'net.luckperms:api:5.4'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

var generateModMetadata = tasks.register('generateModMetadata', ProcessResources) {
    var replaceProperties = [
            mod_version: mod_version
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from 'src/main/templates'
    into 'build/generated/sources/modMetadata'
}
sourceSets.main.resources.srcDir generateModMetadata
neoForge.ideSyncTask generateModMetadata

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
